{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "springboot-web-application.fullname" . }}-configmap'
  labels:
    {{- include "springboot-web-application.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap }}
  {{$key}}: {{ $val | quote}}
  {{- end }}
{{- end }}